x = 4
try:
    print(x)
except:
    print('The print command failed ')
else:
    print('The print was successful ')
finally:
    print('one of it happened')